name: Upload Training Package

on:
  push:
    branches:
      - main  # Adjust this if you're using a different branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'  # Adjust to your Python version

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Create package
        run: |
          python setup.py sdist --formats=gztar

      - name: Upload to GCS
        run: |
          echo "Installing Google Cloud SDK..."
          echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] http://packages.cloud.google.com/apt cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
          curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key --keyring /usr/share/keyrings/cloud.google.gpg add -
          sudo apt-get update && sudo apt-get install google-cloud-sdk

          # Authenticate with GCP
          echo "${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}" > "${HOME}/gcp-key.json"
          gcloud auth activate-service-account --key-file="${HOME}/gcp-key.json"
          
          # Copy tar file to GCS
          gsutil cp dist/my_training_package-0.2.tar.gz gs://mlops_task_us_central1
