name: CI/CD Pipeline

on:
  push:
    paths:
      - 'tuning.py'
      - 'evaluation.py'
      - 'deployment.py'
      - 'my_training_package/**' 
    branches:
      - main  

jobs:
  pre_run_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Pre-run Tests
        run: |
          python 'test_pre_run.py'

  build:
    runs-on: ubuntu-latest
    needs: pre_run_tests
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'  

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Create package
        run: |
          python setup.py sdist --formats=gztar

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      - name: Upload to GCS
        uses: google-github-actions/upload-cloud-storage@v2
        with:
          path: dist/my_training_package-0.2.tar.gz
          destination: mlops_task_us_central1

      - name: Run Hyperparameter Tuning
        run: |
          
          # Running tuning script
          python tuning.py

      - name: Run Model Evaluation
        run: |
          python evaluation.py  # Running evaluation script

      - name: Deploy Best Model
        run: |
          python deployment.py  # Running deployment script
